# basic options
title: TES Modeling Toolkit v1.0-Prelim.
#author: xyz
email: smakarov@mgh.harvard.edu nummenma@nmr.mgh.harvard.edu wawartman@wpi.edu
description: Please direct support requests to Will Wartman at wawartman@wpi.edu
#twitter_username: __
#github_username:  __

# Build settings
markdown: kramdown
theme: minima
